[dependencies]

[package]
  cjc-version = "0.59.6"
  compile-option = ""
  description = "嵌入资源文件(类似go embed)"
  link-option = ""
  name = "embed"
  output-type = "static"
  override-compile-option = ""
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  include =["src"]
  license = ["MulanPSL2"]
  authors = ["ystyle"]
  repository = ["https://github.com/ystyle/cj-sonyflake.git"]
  package-configuration = {}


[target.x86_64-unknown-linux-gnu.bin-dependencies]
path-option = [ "${CANGJIE_STDX_PATH}" ]

[target.x86_64-w64-mingw32.bin-dependencies]
path-option = [ "${CANGJIE_STDX_PATH}" ]

